INSERT OR IGNORE INTO users (name, keep_score, past_mesos, months) VALUES
('test', 0, 3, 8);

INSERT OR IGNORE INTO exercises (name, muscle_group) VALUES
('incline bench press', 'chest'),
('pec dec', 'chest'),
('machine chest press', 'chest'),
('incline dumbbell press', 'chest'),
('low incline dumbbell press', 'chest'),
('smith machine row', 'back'),
('deadlift', 'back'),
('machine t-bar row', 'back'),
('assisted pull-up', 'back'),
('chest supported row', 'back'),
('freemotion curl', 'biceps'),
('leg press', 'quads'),
('calf press machine', 'calves'),
('leg press calves', 'calves'),
('machine lateral raise', 'shoulders'),
('cable tricep pushdown', 'triceps'),
('machine preacher curl', 'biceps'),
('straight arm pulldown', 'back'),
('barbell skullcrusher', 'triceps'),
('machine crunch', 'abs'),
('leg extension', 'quads'),
('cross body cable lateral raise', 'shoulders'),
('single arm tricep pushdown', 'triceps'),
('incline dumbbell curl', 'biceps'),
('lying leg raise', 'abs'),
('ez bar preacher curl', 'biceps'),
('cable overhead extension', 'triceps'),
('dumbbell lateral raise', 'shoulders'),
('back raise', 'hamstrings'),
('barbell squat', 'quads'),
('walking lunges', 'quads'),
('sissy squat', 'quads');
