services:
  app:
    image: python:3.13
    container_name: hypertrophy-app
    hostname: hypertrophy-app
    restart: unless-stopped
    ports:
      - 8501:8501
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && streamlit run 01_Current_Workout.py"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=fitness
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    hostname: hypertrophy-mysql
    container_name: hypertrophy-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: fitness
    volumes:
      - ./mysql:/var/lib/mysql
      - ./helpers/tables.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3601
